services:
  postgresql:
    image: postgres:16.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_service
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always

  consul:
    image: hashicorp/consul:latest
    ports:
      - "8500:8500"
